IIIF-58 Manifest simpele case
viaacode/iiif-manifests pull request #2
Opened 2024-04-09 14:33 UTC by milvld

- Add glassplate API data;
- Add mapped glassplate sample;
- Add JSON-LD frame from Triply sample;
- Add original JSON-LD frame from IIIF;
- Add JSON-LD frame to recreate simplest manifest from IIIF cookbook;
- Add JSON-LD frame to create desired manifest for glassplate;
- Add SPARQL CONSTRUCT query to recreate simplest manifest from IIIF cookbook;
- Add SPARQL CONSTRUCT query to create desired manifest for glassplate.

2024-04-10 10:00 UTC, mielvds requested changes

2024-04-10 10:00 UTC, mielvds commented on examples/5d8nc8tp93_glassplate/5d8nc8tp93_sparql_construct.rq
> +                      dc:format "image/jpeg" .
Kan je dit niet ophalen uit de `premis:File`instantie?

2024-04-10 10:00 UTC, mielvds commented on examples/5d8nc8tp93_glassplate/5d8nc8tp93_sparql_construct.rq
> +  ?s prov:wasDerivedFrom ?mhRecord ;
```suggestion
  ?s a premis:IntellectualEntity; 
     prov:wasDerivedFrom ?mhRecord ;
```

2024-04-10 10:00 UTC, mielvds commented on examples/5d8nc8tp93_glassplate/5d8nc8tp93_sparql_construct.rq
> +  ?cp org:identifier ?cpId ;
```suggestion
  ?cp a haOrg:ContentPartner; 
      org:identifier ?cpId ;
```

2024-04-10 10:00 UTC, mielvds commented on examples/5d8nc8tp93_glassplate/5d8nc8tp93_sparql_construct.rq
> +  BIND(IRI(CONCAT(STR(?iiifFileUrl),".jph")) AS ?serviceIri)
waarom is de Url in de KG dan niet met .jph?

2024-04-10 10:00 UTC, mielvds commented on examples/5d8nc8tp93_glassplate/iiif-frame-glassplate-manifest.json
> +  "@context": {
Is het geen probleem dat die context wordt over gekopieerd? Mogelijk gaat het ontbreken van de http://iiif.io/api/presentation/3/context.json url voor problemen zorgen, zie https://iiif.io/api/presentation/3.0/#46-linked-data-context-and-extensions.

Ik zou ook een ticket aanmaken voor triply op support@triply.cc over die `Invalid JSON-LD syntax; invalid scoped context.` bij het ophalen van externe contexts in JSON-LD frames.

2024-04-30 14:10 UTC, igloosarecool requested changes
Zie comments op manifest output.

2024-04-30 14:10 UTC, igloosarecool commented on examples/0k26971d59_newspaper/0k26971d59_manifest.json
> +  "viewingDirection": ["left-to-right"],
viewingDirection moet string zijn ipv array: https://iiif.io/api/presentation/3.0/#:~:text=an%20extension.-,The%20value%20must%20be%20a%20string.,-A%20Collection%20may

2024-04-30 14:10 UTC, igloosarecool commented on examples/0k26971d59_newspaper/0k26971d59_manifest.json
> +  "rights": "https://creativecommons.org/licenses/by/4.0/deed.nl",
rights uri moet http zijn ipv https: 'http://creativecommons.org/licenses/.*'

2024-04-30 14:10 UTC, igloosarecool commented on examples/0k26971d59_newspaper/0k26971d59_manifest.json
> +        "@none": ["nl"]
@none zou none moeten zijn.

Detail: Language string, must have a language and value must be an array.
Path: /metadata[0]/value/['@none' does not match any of the regexes: '^[a-zA-Z-][a-zA-Z-]*$', '^none$']

Dit geldt voor alle occurences van @none

2024-04-30 14:10 UTC, igloosarecool commented on examples/0k26971d59_newspaper/0k26971d59_manifest.json
> +  "@context": {
@ context is not of type array. Een array wordt verwacht ipv een hash.

2024-04-30 14:10 UTC, igloosarecool commented on examples/0k26971d59_newspaper/0k26971d59_manifest.json
De full text OCR uit de description van het MAM record ontbreekt als annotation, zie https://github.com/viaacode/iiif-manifests/blob/397fcaf9aa5983787f4a084cb47d8576ff1cbf0e/manifest-templates/newspaper-issue.json#L133

2024-04-30 14:34 UTC, igloosarecool commented on examples/0k26971d59_newspaper/0k26971d59_manifest.json
> +        "@none": ["nl"]
Dit ligt waarschijnlijk aan het feit dat de none alias uit de presentation api context niet correct wordt opgepikt door de validator vanwege https://github.com/viaacode/iiif-manifests/pull/2#discussion_r1584828210

2024-05-15 12:23 UTC, milvld commented on examples/0k26971d59_newspaper/0k26971d59_manifest.json
Ik snap deze niet zo goed; bedoel je dat je de volledige OCR mee in het manifest wil steken? Zijn de URLs die ernaar linken in de Annotation body en via "rendering"/"seeAlso" niet voldoende?

2024-07-17 12:12 UTC, merged